package mobi.mpk.chessandroid.type;


public enum ResultType {

    SUCCESS, ERROR_NOT_YOU_MOVE, ERROR_INCORECT_CELL,
    ERROR_INCORECT_MOVE, ERROR_CELL_HAVE_NOT_FIGURE,
    ERROR_FIGURE_CAN_NOT_MOVE_THIS, ERROR_CELL_HAVE_NOT_YOUR_FIGURE,
    ERROR_OBSTACLES_WAY, ERROR;

}
